### PR TITLE
Updates to the pulsar monitoring schedule

### PR DESCRIPTION
**Pull request by jaycedowell**
Updates to the pulsar monitoring schedule to drop observations of marginal detections and change the overall cadence to 1, 2, and 6 week intervals.

### CODE REVIEW

**Comment by jaycedowell** [comment]
@pratiksan can you re-sort the entries by increasing RA?

**Comment by pratiksan** [comment]
> @pratiksan can you re-sort the entries by increasing RA?

Done

**Comment by jaycedowell** [comment]
The order still looks a little off, like around J2145-0750.

**Comment by jaycedowell** [comment]
I can't tell that anything has changed to fix the sorting.  For example:
```
B0031-07     0:34:08.80   -7:21:53.4   1.0  14  60187
B0053+47     0:56:25.50   +47:56:10.5  1.0  42  60197
J0030+0451   0:30:27.40   +4:51:39.7   2.0  07  60158
J0034-0534   0:34:21.80   -5:34:36.7   2.0  07  60120
J0051+0423   0:51:30.10   +4:22:49.0   1.0  14  60213
J0054+66     0:54:00.00   +66:00:00.0  1.0  42  60153
```
or
```
B2315+21     23:17:57.80  +21:49:48.0  1.0  42  60191
B2327-20     23:30:26.80  -20:05:29.6  1.0  14  60203
B2334+61     23:37:05.70  +61:51:01.5  1.0  42  60159
J2325-0530   23:25:15.30  -5:30:39.0   1.0  42  60199
```
It always seems to be problems associated with the "J" names.

**Pull request merged**
